version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # remove package-lock before updating npm, otherwise not all dependencies will install
      - rm package-lock.json
      # update npm to 5.6.0 due to package-lock bug: https://github.com/npm/npm/issues/18135
      - npm install --silent --progress=false -g npm
      # install dependencies
      - npm install --silent --progress=false -g serverless
      - npm install --silent --progress-false
      - npm --version
  build:
    commands:
      # unit tests
      - npm test
      # deploy integration testing environment
      - serverless deploy --stage integrationtest -v
      # integration tests
      - npm run itest
      # create directory for deployment packages
      - mkdir artifacts
      # create staging deployment package
      - mkdir artifacts/stg
      - serverless package --package artifacts/stg --stage stg -v
      # create prod deployment package
      - mkdir artifacts/prod
      - serverless package --package artifacts/prod --stage prod -v
  post_build:
    commands:
      # tear down integration testing environment
      - serverless remove --stage integrationtest -v

artifacts:
  files:
    # export artifacts needed for staging and prod deployments to an S3 bucket
    - artifacts/**/*
    - serverless.yml
    - deploy.sh